# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: bbrainfuckk.qorx
PackageVersion: 1.0.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: qorx.exe
    PortableCommandAlias: qorx
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/bbrainfuckk/qorx/releases/download/v1.0.1/qorx-v1.0.1-windows-x64.zip
    InstallerSha256: EE3D557C7252676930796C4991F6B28F50113805682CC26DB18E3F8ADD4DDE3C
ManifestType: installer
ManifestVersion: 1.9.0
