name: qorx
base: core24
version: "1.0.5"
summary: Qorx language, compiler, and local runtime
description: |
  Qorx is a programming language, compiler, portable bytecode runtime,
  and local context resolver.

grade: stable
confinement: strict

parts:
  qorx:
    plugin: rust
    source: https://github.com/bbrainfuckk/qorx.git
    source-tag: v1.0.5

apps:
  qorx:
    command: bin/qorx
    plugs:
      - home
      - removable-media
      - network
