PackageIdentifier: Qorx.Qorx
PackageVersion: 1.0.5
PackageLocale: en-US
Publisher: Qorx
PackageName: Qorx
License: AGPL-3.0-only
ShortDescription: Qorx language, compiler, bytecode runtime, and local context resolver.
PackageUrl: https://github.com/bbrainfuckk/qorx
ManifestType: defaultLocale
ManifestVersion: 1.9.0
