# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: bbrainfuckk.qorx
PackageVersion: 1.0.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: qorx.exe
    PortableCommandAlias: qorx
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/bbrainfuckk/qorx/releases/download/v1.0.2/qorx-v1.0.2-windows-x64.zip
    InstallerSha256: ECE330A4303DE133C7BC87F87F8824D8F71054D78FCEE86E1ACE7EE7D3FD45D6
ManifestType: installer
ManifestVersion: 1.9.0
